### ISSUE TITLE
Possible memory/processing leak via Xorg

### ISSUE THREAD

**Issue by AdamColligan** [leszakk/orient#1]
Hardware: HP Envy x360 15t | Intel graphics
OS: Ubuntu 15.04 Vivid | Systemd
Orient configuration: script added to startup list

After running for a few hours, I noticed that Xorg was consuming 5.6GB of RAM and 8 percent CPU. While the Orient process was not consuming significant memory, it did have some noticeable CPU time associated with it.  

The Xorg.0.log file had grown to over 1.2GB. Its tail messages were

[ 13571.659] (II) modeset(0): Modeline "1920x1080"x0.0  141.00  1920 1958 2018 2104  1080 1084 1090 1116 +hsync -vsync (67.0 kHz eP)
[ 13571.659] (II) modeset(0): Modeline "1920x1080"x0.0   94.00  1920 1958 2018 2104  1080 1084 1090 1116 +hsync -vsync (44.7 kHz e)
[ 13571.663] (II) modeset(0): EDID vendor "CMN", prod id 5561
[ 13571.663] (II) modeset(0): Printing DDC gathered Modelines:
[ 13571.663] (II) modeset(0): Modeline "1920x1080"x0.0  141.00  1920 1958 2018 2104  1080 1084 1090 1116 +hsync -vsync (67.0 kHz eP)
[ 13571.663] (II) modeset(0): Modeline "1920x1080"x0.0   94.00  1920 1958 2018 2104  1080 1084 1090 1116 +hsync -vsync (44.7 kHz e)
[ 13571.668] (II) modeset(0): EDID vendor "CMN", prod id 5561
[ 13571.668] (II) modeset(0): Printing DDC gathered Modelines:
[ 13571.668] (II) modeset(0): Modeline "1920x1080"x0.0  141.00  1920 1958 2018 2104  1080 1084 1090 1116 +hsync -vsync (67.0 kHz eP)
[ 13571.668] (II) modeset(0): Modeline "1920x1080"x0.0   94.00  1920 1958 2018 2104  1080 1084 1090 1116 +hsync -vsync (44.7 kHz e)

When I stopped the Orient process, I saw an immediate spin-down of my CPU fan and a reduction of the % CPU utilization for Xorg to the low single digits. Restarting the Orient process brought the Xorg process back up to around 9 percent CPU.

Ending the Orient process again brought the Xorg CPU use down to a sane level, but it still retained almost 6GB of memory allocation indefinitely.

**Comment by leszakk** [comment]
Thank's for the feedback. I think it has something to do with the xrandr implementation. Also, I'm working on a compatibility list. Does orient work on the x360? If not, could you give me some info on the accelerometer so I can add compatibility?

**Comment by AdamColligan** [comment]
It does work (except for the fact that an upside-down orientation, useful for tent mode, is not implemented in the script).

**Comment by leszakk** [comment]
memory leak was due to xrandr being called on every loop instead of only when needed. fixed that and added tent mode

**Comment by AdamColligan** [comment]
Cool; I've reinstalled and will let you know if there are any more issues along this line. Orient does now seem to be using 1% of CPU all the time, and if I leave open gnome-system-monitor and watch it, Orient is actually accumulating CPU time faster than the system monitor GUI. But I really don't know whether that should be unexpected or cause for concern.

**Comment by leszakk** [comment]
Fixed in latest commit
